spring:
  application:
    name: java_t1
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: '0000'
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false
  batch:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

logging:
  level:
    ROOT: ${LOG_LEVEL:INFO}
    ru.t1.java.demo: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG

t1:
  scan-path: ru.t1.java.demo
  metrics:
    time-limit: 7000  # время в миллисекундах
    enabled: true
    include-packages:
      - ru.t1.java.demo.service
      - ru.t1.java.demo.controller
    exclude-methods:
      - getClientById
      - getAllClients
      - getAccountById
      - getAllAccounts
      - getTransactionById
      - getAllTransactions
