spring:
  application:
    name: java_t1
  datasource:
    url: jdbc:postgresql://localhost:5432/t1
    username: postgres
    password: '0000'
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false
  batch:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:

      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          provider_disables_autocommit: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

logging:
  level:
    ROOT: ${LOG_LEVEL:INFO}
    ru.t1.java.demo: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG

t1:
  scan-path: ru.t1.java.demo
